version: '3.9'
services:
  backend:
    image: swiftext-backend-dev
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    env_file:
      - .env

  dynamo-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
