services:
  swiftext-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - appnetwork
    env_file:
      - .env
    volumes:
      - storage-data:/app/files

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - appnetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - appnetwork
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
      - dynamo-data:/home/dynamodblocal

networks:
  appnetwork:
    driver: bridge

volumes:
  dynamo-data: {}
  postgres-data: {}
  storage-data: {}
